using CWMAssistApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Identity.Client;
using CWMAssistApp.Data.Entity;
using Microsoft.AspNetCore.Identity;
using CWMAssistApp.Data;

namespace CWMAssistApp.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private UserManager<AppUser> _userManager;
        private ApplicationDbContext _context;
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, UserManager<AppUser> userManager, ApplicationDbContext context)
        {
            _logger = logger;
            _userManager = userManager;
            _context = context;
        }

        public IActionResult Index()
        {
            var vm = new IndexVM();
            var user = _userManager.Users.SingleOrDefault(x => x.UserName == HttpContext.User.Identity.Name);

            vm.TotalAppointmentCount = _context.Appointments.Count(x => x.CompanyId == user.CompanyId && x.Status && x.StartDate < DateTime.Now);
            vm.TotalVisitorCount = _context.CustomerAppointments.Count(x => x.CompanyId == user.CompanyId && x.Status && x.AppointmentDate < DateTime.Now);
            vm.TotalUniqueVisitorCount = _context.Customers.Count(x => x.StoreId == user.CompanyId);

            return View(vm);
        }

        [HttpPost]
        public JsonResult GetVisitorChartInfo()
        {
            var model = new VisitorChartModel();
            try
            {
                var user = _userManager.Users.SingleOrDefault(x => x.UserName == HttpContext.User.Identity.Name);
                var _now = DateTime.Now;
                var startDate = _now;
                var endDate = new DateTime(_now.Year, _now.Month, _now.Day, 23, 59, 59);

                var dayOfWeek = _now.DayOfWeek;

                startDate = dayOfWeek == 0 ? _now.AddDays(-6) : _now.AddDays(1 - (int)dayOfWeek);

                startDate = new DateTime(startDate.Year, startDate.Month, startDate.Day, 0, 0, 0);

                var thisWeekCustomerAppointment =
                    _context.CustomerAppointments.Where(x => x.CompanyId == user.CompanyId && x.AppointmentDate > startDate && x.AppointmentDate < endDate && x.Status);

                model.ThisWeekVisitorCount = thisWeekCustomerAppointment.Count();

                var dayDiff = endDate - startDate;

                var thisWeekVisitorDayList = new int[dayDiff.Days+1];

                foreach (var customerAppointment in thisWeekCustomerAppointment)
                {
                    var diff = customerAppointment.AppointmentDate.Date - startDate.Date;
                    thisWeekVisitorDayList[diff.Days] += 1;
                }
                model.ThisWeekVisitorDayList = thisWeekVisitorDayList;

                var lastWeekStartDate = startDate.AddDays(-7);
                var lastWeekEndDate = startDate.AddDays(-1);

                lastWeekEndDate = new DateTime(lastWeekEndDate.Year, lastWeekEndDate.Month, lastWeekEndDate.Day, 23, 59,
                    59);

                var lastWeekCustomerAppointment =
                    _context.CustomerAppointments.Where(x => x.CompanyId == user.CompanyId && x.AppointmentDate > lastWeekStartDate && x.AppointmentDate < lastWeekEndDate && x.Status);

                var lastWeekVisitorDayList = new int[7];
                foreach (var customerAppointment in lastWeekCustomerAppointment)
                {
                    var diff = customerAppointment.AppointmentDate.Date - lastWeekStartDate.Date;
                    lastWeekVisitorDayList[diff.Days] += 1;
                }
                model.LastWeekVisitorDayList = lastWeekVisitorDayList;

                var customerCountForRate = 0;
                var thisWeekCustomerCount = 0;
                var lastWeekCustomerCount = 0;
                for (var i = 0; i < thisWeekVisitorDayList.Count(); i++)
                {
                    thisWeekCustomerCount += thisWeekVisitorDayList[i];
                    lastWeekCustomerCount += lastWeekVisitorDayList[i];
                }

                customerCountForRate = thisWeekCustomerCount - lastWeekCustomerCount;
                model.WeekRate = (customerCountForRate * 100) / (lastWeekCustomerCount == 0 ? 1 : lastWeekCustomerCount);
                model.ArrowUp = customerCountForRate >= 0;

            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }

            
            return Json(model);
        }

        public IActionResult Privacy()
        {
            var model = new DummyDataModel();
            return View(model);
        }
        [HttpPost]
        public IActionResult Privacy(DummyDataModel model)
        {
            var nameList = new List<string>()
            {"JALE",
                "ALİ",
                "MAHMUT",
                "MANSUR KÜRŞAD",
                "GAMZE",
                "MİRAÇ",
                "YÜCEL",
                "KUBİLAY",
                "HAYATİ",
                "BEDRİYE MÜGE",
                "BİRSEN",
                "SERDAL",
                "BÜNYAMİN",
                "ÖZGÜR",
                "FERDİ",
                "REYHAN",
                "İLHAN",
                "GÜLŞAH",
                "NALAN",
                "SEMİH",
                "ERGÜN",
                "FATİH",
                "ŞENAY",
                "SERKAN",
                "EMRE",
                "BAHATTİN",
                "IRAZCA",
                "HATİCE",
                "BARIŞ",
                "REZAN",
                "FATİH",
                "FUAT",
                "GÖKHAN",
                "ORHAN",
                "MEHMET",
                "EVREN",
                "OKTAY",
                "HARUN",
                "YAVUZ",
                "PINAR",
                "MEHMET",
                "UMUT",
                "MESUDE",
                "HÜSEYİN CAHİT",
                "HAŞİM ONUR",
                "EYYUP SABRİ",
                "MUSTAFA",
                "MUSTAFA",
                "UFUK",
                "AHMET ALİ",
                "MEDİHA",
                "HASAN",
                "KAMİL",
                "NEBİ",
                "ÖZCAN",
                "NAGİHAN",
                "CEREN",
                "SERKAN",
                "HASAN",
                "YUSUF KENAN",
                "ÇETİN",
                "TARKAN",
                "MERAL LEMAN",
                "ERGÜN",
                "KENAN AHMET",
                "URAL",
                "YAHYA",
                "BENGÜ",
                "FATİH NAZMİ",
                "DİLEK",
                "MEHMET",
                "TUFAN AKIN",
                "MEHMET",
                "TURGAY YILMAZ",
                "GÜLDEHEN",
                "GÖKMEN",
                "BÜLENT",
                "EROL",
                "BAHRİ",
                "ÖZEN ÖZLEM",
                "SELMA",
                "TUĞSEM",
                "TESLİME NAZLI",
                "GÜLÇİN",
                "İSMAİL",
                "MURAT",
                "EBRU",
                "TÜMAY",
                "AHMET",
                "EBRU",
                "HÜSEYİN YAVUZ",
                "BAŞAK",
                "AYŞEGÜL",
                "EVRİM",
                "YASER",
                "ÜLKÜ",
                "ÖZHAN",
                "UFUK",
                "AKSEL",
                "FULYA",
                "BURCU",
                "TAYLAN",
                "YILMAZ",
                "ZEYNEP",
                "BAYRAM",
                "GÜLAY",
                "RABİA",
                "SEVDA",
                "SERHAT",
                "ENGİN",
                "ASLI",
                "TUBA",
                "BARIŞ",
                "SEVGİ",
                "KALENDER",
                "HALİL",
                "BİLGE",
                "FERDA",
                "EZGİ",
                "AYSUN",
                "SEDA",
                "ÖZLEM",
                "ÖZDEN",
                "KORAY",
                "SENEM",
                "ZEYNEP",
                "EMEL",
                "BATURAY KANSU",
                "NURAY",
                "AYDOĞAN",
                "ÖZLEM",
                "DENİZ",
                "İLKNUR",
                "TEVFİK ÖZGÜN",
                "HASAN SERKAN",
                "KÜRŞAT",
                "SEYFİ",
                "ŞEYMA",
                "ÖZLEM",
                "ERSAGUN",
                "DİLBER",
                "MESUT",
                "ELİF",
                "MUHAMMET FATİH",
                "ÖZGÜR SİNAN",
                "MEHMET ÖZGÜR",
                "MAHPERİ",
                "ONUR",
                "İBRAHİM",
                "FATİH",
                "SEVİL",
                "SÜHEYLA",
                "VOLKAN",
                "İLKAY",
                "İLKNUR",
                "ZÜMRÜT ELA",
                "HALE",
                "YENER",
                "SEDEF",
                "FADIL",
                "SERPİL",
                "ZÜLFİYE",
                "SULTAN",
                "MUAMMER HAYRİ",
                "DERVİŞ",
                "YAŞAR GÖKHAN",
                "TUBA HANIM",
                "MEHRİ",
                "MUSTAFA FERHAT",
                "SERDAR",
                "MUSTAFA ERSAGUN",
                "ONAT",
                "ŞÜKRÜ",
                "OLCAY BAŞAK",
                "SERDAR",
                "YILDIZ",
                "AYDIN",
                "ALİ HALUK",
                "NİHAT BERKAY",
                "İSMAİL",
                "AYKAN",
                "SELÇUK",
                "MEHMET",
                "NEZİH",
                "MUSTAFA",
                "TİMUR",
                "ERHAN",
                "MUSTAFA",
                "MUTLU",
                "MEHMET HÜSEYİN",
                "İSMAİL EVREN",
                "OSMAN ERSEGUN",
                "MEHMET",
                "ELİF",
                "SERKAN",
                "MESUT",
                "MEHMET HİLMİ",
                "ASUDAN TUĞÇE",
                "AHMET GÖKHAN",
                "BAŞAK",
                "CEYHAN",
                "MUHAMMET TAYYİP",
                "ESİN",
                "ZEYNEP GÖKÇE",
                "EVRİM",
                "YASİN",
                "SALİHA",
                "DENİZ",
                "BELGİN",
                "ÖZLEM",
                "GONCA",
                "ESRA",
                "SEÇKİN",
                "ESRA",
                "FATİH",
                "MUSTAFA",
                "FEVZİYE",
                "MUSTAFA ARİF",
                "BİRGÜL",
                "ÖZLEM",
                "ÖZLEM",
                "FUNDA",
                "BERFİN",
                "DEMET",
                "SONAY",
                "SERÇİN",
                "ALMALA PINAR",
                "ÜMİT",
                "SENEM",
                "DENİZ",
                "MÜNEVER",
                "HATİCE",
                "ÖZLEM",
                "ÖZLEM",
                "ALİ SEÇKİN",
                "COŞKUN",
                "ÖZGE",
                "ZELİHA",
                "PINAR",
                "AYBÜKE",
                "HASİBE",
                "GÜRKAN",
                "ZÜHAL",
                "NAZIM",
                "ZEYNEP",
                "OSMAN",
                "AYLA",
                "BEYZA",
                "ELİF",
                "ERAY",
                "DİANA",
                "TUBA",
                "SEMRA",
                "VELAT",
                "BELGİN EMİNE",
                "SİBEL",
                "GÖKMEN ALPASLAN",
                "BENHUR ŞİRVAN",
                "DİLEK",
                "HANDE",
                "ŞAHABETTİN",
                "MİRAY",
                "ZERRİN",
                "İLKNUR",
                "ELİF",
                "MÜMTAZ",
                "TUĞBA",
                "DİLEK",
                "MEHMET BURHAN",
                "FUAT",
                "NİHAL",
                "AYŞEGÜL",
                "SEMA",
                "ZAFER",
                "NURSEL",
                "GÜLPERİ",
                "BİLGE",
                "FATİH",
                "CENGİZ",
                "SİMGE",
                "SEMA NİLAY",
                "EMİNE",
                "RİFAT CAN",
                "SİNAN",
                "LATİFE",
                "MEHMET",
                "NURDAN",
                "MELTEM",
                "ÜLKÜHAN",
                "HASAN",
                "GÜLDEN",
                "SAMET",
                "BERNA",
                "ÖZLEM",
                "NAFİYE",
                "KENAN",
                "SERKAN FAZLI",
                "NURSEL",
                "ABDULLAH",
                "ERGÜL",
                "HASAN",
                "MUSTAFA",
                "SEBAHAT",
                "EMİNE",
                "ERDAL",
                "LEZİZ",
                "BİRSEN",
                "TUBA",
                "AYŞEN",
                "EBRU",
                "TAYFUR",
                "MELTEM",
                "SERHAT",
                "AYCAN ÖZDEN",
                "ELİF",
                "SEVGÜL",
                "SELDA",
                "IŞIL",
                "SİBEL",
                "JÜLİDE ZEHRA",
                "BERİL GÜLÜŞ",
                "İNCİ",
                "ENGİN",
                "GÜLBAHAR",
                "MÜBECCEL",
                "NURDAN",
                "HANDE",
                "ÖZNUR",
                "HANDAN",
                "OSMAN TURGUT",
                "EMİN TONYUKUK",
                "NEJDET",
                "MUSTAFA",
                "GÜLİZ",
                "İPEK",
                "NİHAL",
                "MELDA",
                "DERYA",
                "DEMET",
                "MAHMUT",
                "EMEL",
                "ÖZNUR",
                "SONGÜL",
                "RESA",
                "GAMZE",
                "ÜMİT",
                "DENİZ",
                "MUAMMER MÜSLİM",
                "ÖMER FARUK",
                "TUĞÇE",
                "VELİ ENES",
                "ZAHİDE",
                "NURETTİN İREM",
                "SEDAT",
                "REMZİYE",
                "SİBEL",
                "İLKNUR",
                "YASEMİN",
                "AYLİN",
                "EMEL",
                "EMEL CENNET",
                "ŞAFAK",
                "METİN",
                "SÜLEYMAN",
                "MUKADDES",
                "BARIŞ",
                "MEHMET ALİ",
                "TEVFİK",
                "SERDAR",
                "EMİNE",
                "MÜRŞİT",
                "MUTLU",
                "FEZA",
                "İBRAHİM TAYFUN",
                "SERKAN",
                "AHMET SERKAN",
                "FATMA",
                "BERKER",
                "SERDAR",
                "KUBİLAY",
                "ERKAN",
                "KERİM",
                "İLKNUR",
                "SERKAN",
                "MUSTAFA",
                "RUKİYE",
                "GÖKTEN",
                "SEZGİ",
                "TUĞBA",
                "MURAT",
                "HATİCE",
                "HATİCE EYLÜL",
                "AYŞE GÜL",
                "NEVİN",
                "HABİBE",
                "KEZBAN",
                "AYSEL",
                "TALHA",
                "DUYGU",
                "GÖZDE",
                "FIRAT",
                "EBRU",
                "GÜLEN ECE",
                "SİBEL",
                "FULYA",
                "VEDAT",
                "HARUN",
                "FİLİZ",
                "NURAY",
                "ŞİRİN",
                "ÖZLEM",
                "BURCU",
                "PINAR",
                "HATUN",
                "CEYDA",
                "BURCU",
                "AYŞE",
                "ALPER",
                "FEYZA",
                "HACI MURAT",
                "MÜCELLA",
                "FEYZAHAN",
                "ŞENAY",
                "MERİH",
                "YUSUF",
                "ARDA",
                "EVRE",
                "KONURALP",
                "KIVANÇ",
                "EMİNE",
                "VOLKAN",
                "NİHAT",
                "RENGİN ASLIHAN",
                "EMRE",
                "ARİFE ESRA",
                "SEDAT",
                "MURAT",
                "CEM",
                "ERHAN",
                "ÖMÜR",
                "UMUT CAN",
                "MUSTAFA NAFİZ",
                "DAMLA",
                "MÜSLİM",
                "ABDULKADİR",
                "SAADET",
                "REZZAN",
                "SEDAT",
                "İBRAHİM",
                "LEYLA",
                "TÜLAY",
                "ENDER",
                "YELİZ",
                "ÖZGÜL",
                "HALE",
                "BERÇEM",
                "MUSTAFA",
                "TUBA",
                "SABAHATTİN",
                "ŞAFAK",
                "EVRİM",
                "REŞAT",
                "MUMUN",
                "FUNDA ÖZLEM",
                "NUR",
                "METE",
                "TÜLAY",
                "ÖZLEM",
                "HATİCE NİLDEN",
                "MELTEM",
                "EDA",
                "MELTEM",
                "MUSTAFA",
                "YURDUN",
                "SEMA",
                "TUBA",
                "SERPİL",
                "CENK",
                "TANER",
                "ZEKERİYA",
                "MUHAMMED ALİ",
                "TUĞRUL",
                "YÜCEL",
                "ESMA ÖZLEM",
                "AHMET",
                "SEVDE NUR",
                "SAMİ",
                "GAMZE",
                "GÜLSÜM",
                "SERHAT",
                "BARIŞ",
                "GÜLSEREN",
                "SULTAN",
                "İLKER",
                "DERAM",
                "AHMET",
                "BALA BAŞAK",
                "FEVZİ FIRAT",
                "GÖZDE",
                "FERHAN"
            };
            var surnameList = new List<string>() { "ŞEN",
"KANDEMİR",
"ÇEVİK",
"ERKURAN",
"TÜTEN",
"ÖZTÜRK",
"YÜZBAŞIOĞLU",
"VURAL",
"YÜCEL",
"SÖNMEZ",
"ERTEKİN",
"DEDE",
"UYANIK",
"ASLAN",
"AKBULUT",
"ORHON",
"UZ",
"YAVUZ",
"ERDEM",
"KULAÇ",
"KAYA",
"SELVİ",
"AKPINAR",
"ABACIOĞLU",
"ÇAY",
"IŞIK",
"ÖZER",
"ÖZDEMİR",
"ÖZTÜRK",
"TAHTACI",
"BÜYÜKCAM",
"KULAKSIZ",
"AKSEL",
"EROĞLU",
"KARAKUM",
"DAL",
"ÖCAL",
"AYHAN",
"YİĞİT",
"YARBİL",
"CANACANKATAN",
"GÜMÜŞAY",
"MURT",
"HALHALLI",
"ULUÖZ",
"ŞEYHANLI",
"ÇALIŞKANTÜRK",
"YILMAZ",
"SARAÇOĞLU",
"SEZER",
"DOĞAN",
"DEMİR",
"KAYAYURT",
"SÜRÜM",
"YAVAŞİ",
"TURGUT",
"ŞEN TANRIKULU",
"BARBAROS",
"ALDİNÇ",
"TEKİN",
"GÜLŞAN",
"KÜFECİLER",
"ALMACIOĞLU",
"ÇİLDİR",
"TÜRKDOĞAN",
"KAYA",
"ÖNER",
"ŞELİMAN",
"YAMAN",
"ATİK",
"YİĞİT",
"GİRAY",
"YALÇINKAYA",
"KILIÇ",
"ŞENTÜRK",
"KARABAĞ",
"DEĞİRMENCİ",
"BODUROĞLU",
"YILDIZ",
"GÜLER",
"ERASLAN",
"ÜZER",
"PİŞİRGEN",
"ADANIR",
"KOÇ",
"KORKMAZ",
"YENİDOĞAN",
"AYDOĞAN",
"ACARBULUT",
"ERGE",
"ERDOĞAN",
"ÖĞÜT AYDIN",
"KUŞKU",
"KUCUR TÜLÜBAŞ",
"PEKTAŞ",
"KAYACAN",
"GÜLEN",
"DOĞAN",
"AYDIN BADILLIOĞLU",
"GÜLEN AKKÜÇÜK",
"CANDAN",
"TEMEL",
"YENİGÜN",
"YILDIRIM",
"BEDER",
"AKINCI",
"ÖZDEMİR",
"ONUK",
"AYDOĞAN",
"YILMAZ",
"AKCAN ATASOY",
"SARAÇOĞLU ÇEKİÇ",
"CÖMERT",
"TOPAL",
"KARAHAN",
"ŞAHİN",
"ÇETİN",
"YILMAZ İNAL",
"AYTAÇ",
"YILDIZ ALTUN",
"KİŞİ",
"GÜNDÜZ",
"ÖZKURT PÜRCÜ",
"AK",
"URFALI",
"KARAMAN",
"MEMETOĞLU",
"KAZBEK",
"KİREÇÇİ",
"AKIN",
"YADİGAROĞLU",
"YÜKSEL",
"ÖZÇELİK ORAL",
"BABUŞ",
"KAPLAN",
"AKÖZ",
"KARTAL",
"BİLGİÇ",
"ERDEN",
"TUĞCUGİL",
"KUMRAL",
"ERBAŞ",
"ORAL",
"KILAÇ",
"CENGİZ",
"YILDIRIM",
"KUTLUCAN BAĞCI",
"BALABAN",
"KAYA",
"BALCI",
"TÜFEKÇİ",
"ATAY",
"YARAR",
"SEVER",
"YILDIRIM",
"ARSLAN KAŞDOĞAN",
"ARKAN",
"TUTAŞ",
"ÖZTÜRK",
"HAVAS",
"SEÇİR",
"YILDIZ",
"SOYKAMER",
"BEKTAŞ",
"BERK",
"GÜL",
"GEDİK YILMAZ",
"CENGİZ",
"ÇOLAK",
"BULUT",
"SARI",
"AKYOL",
"BAĞCIK",
"KUTLUYURDU",
"DEMİRGAN",
"YİĞİT KUPLAY",
"GERİLMEZ",
"DÜZKALIR",
"KÖKSOY",
"GÜLŞEN",
"AKAR",
"ÖZDOĞAN",
"TÖNGE",
"YASA",
"ÖNVERMEZ",
"YILDIRIM",
"BİÇER",
"KARADEMİR",
"ALIMLI",
"AKGÜL",
"HANCIOĞLU",
"BATÇIK",
"OLPAK",
"BOLAT",
"ARSLAN",
"SİĞA",
"MERCAN",
"BOZKURTER",
"GÜLER",
"ERGİNEL",
"ŞAHİN",
"KADAK",
"GÜNEY KOCABAŞ",
"GAYRETLİ AYDIN",
"HEPKAYA",
"BAYRAM",
"KANIK YÜKSEK",
"KULAK GEDİK",
"AKCAN PAKSOY",
"ESER",
"KILIÇ YILDIRIM",
"GİDER",
"KURT",
"ELLİALTI",
"DEMİRTAŞ",
"ARGA",
"BAŞKAN VURALKAN",
"ALUÇLU",
"MUTLU",
"ŞATIR ERTEM",
"ENGİZ",
"ÇİPE",
"UYSAL",
"BAŞER",
"ARSLAN",
"GÖZKAYA",
"ULUTAŞ",
"PİRİM",
"ÜSTÜN",
"KIZMAZOĞLU",
"ULUBA",
"ARSLAN",
"KARAOĞLU",
"ÖZSOY",
"YALÇIN",
"SAF",
"VURAL",
"DEMİRTAŞ",
"GENÇPINAR",
"AKASLAN",
"UYĞUN",
"ATAY",
"ÖNDER SİVİŞ",
"BAYMAK",
"ATAY",
"GÜVENÇ",
"AKCA ÇAĞLAR",
"ÖZCAN",
"ERDEM ÖZCAN",
"BAŞMAN",
"YANNİ",
"ÜNAL",
"GÜNDOĞDU",
"ÇELİK",
"USTA GÜÇ",
"TANRIVERDİ YILMAZ",
"TAŞKIN",
"ÇETİN",
"YILMAZ ÇİFTDOĞAN",
"GAZETECİ TEKİN",
"SARİ",
"KARAKOYUN",
"KARAKUŞ EPÇAÇAN",
"EKİCİ",
"AYDINER",
"AKTAŞ",
"BELGEMEN",
"ÇETİN",
"OFLAZ",
"BUĞRUL",
"BAYSOY",
"BÜKÜLMEZ",
"YILMAZ",
"BIÇAKÇI",
"KARA",
"TİMURTAŞ DAYAR",
"ATEŞ",
"BİNBOĞA",
"KIZILTEPE",
"KAYA",
"ABSEYİ",
"AMİROVA UÇAN",
"ÖZTÜRK",
"TAŞ",
"CEYLAN",
"KILIÇ",
"EROL",
"TAYFUN",
"KAYA",
"KARAKURT",
"BUDUNOĞLU",
"ÖZER",
"SAYGIN",
"ERYAVUZ",
"POLAT ÇİÇEK",
"YILMAZ",
"ÇELİK",
"ÜNSAL",
"ALPINAR",
"CİNDEMİR",
"AKDUMAN",
"UYAR",
"TÜLPAR",
"AZAK",
"EREN",
"GÖZCÜ",
"BAYSAL",
"TUNCEL",
"ÇETEMEN",
"YILMAZ",
"GİNİŞ",
"UZUN",
"NASIROĞLU",
"SEZGİN",
"ÖZTÜRK",
"YILDIRIM",
"UZUN",
"BULUR",
"DUYSAK",
"YENİN",
"DEMİREL",
"SAK",
"KOCABAŞ",
"SARAÇ",
"ALKURT KAYIKÇI",
"YURT",
"İLKAY",
"TAVŞAN",
"ALAY",
"ERTEM",
"ÖZEL",
"GENÇ",
"UĞUZ",
"EVİK",
"GENÇ TALAS",
"EKER",
"ÇİMEN",
"ÇIRAKOĞLU",
"DEMİR GÖÇMEN",
"ALPAYCI",
"AK",
"ÇELİK",
"ERCAN",
"ALTUN",
"KILIÇ",
"SARP",
"SÖKER",
"KÖSE",
"BARÇAK",
"ÖZEKLİ MISIRLIOĞLU",
"BOLAÇ",
"ASLANALP",
"ÖRNEK",
"AKDOĞAN",
"ÖZÇELİK",
"ERTÜRKLER",
"SARAL",
"ÖZKAN",
"DEMİRHAN",
"ASLANKARA",
"EMLAKÇIOĞLU",
"ÖZTÜRK",
"ESER",
"ÖDEN",
"DEMİRAY",
"AYHAN",
"YAĞCI",
"AVCI",
"BAYGELDİ",
"BÜKÜM",
"DİNCER",
"DOĞAN",
"EKİZ",
"ŞAHİNER",
"ŞENGÜL",
"İLGÜN",
"AŞIK",
"ÖZKAN",
"ŞİRZAİ",
"ÖCALAN",
"KABA",
"TÜLÜCE",
"AYTEKİN",
"KAYA",
"DÜGER",
"METİNEREN",
"BULUT",
"ŞAHİN DUYAR",
"ÇETİN",
"BÖLÜK",
"GÖZAÇAN",
"BOZKURT",
"ÖNEY KURNAZ",
"AY GÜNEY",
"KÖYLÜ",
"ÖZMEN SÜNER",
"TALAN",
"DUMLU",
"ZORLU KARAYİĞİT",
"KÖYCÜ",
"UYGUR",
"KABACAOĞLU",
"TOPALOĞLU",
"AYIK",
"DEMİR",
"ERDEM",
"KARAMANLI",
"SADİ AYKAN",
"OKTAY",
"YURTLU",
"SALMAN SEVER",
"CİRİT KOÇER",
"SORGUN EVCİLİ",
"NURÇİN",
"BAŞKAN",
"KAZANCI",
"KIYAK YILMAZ",
"METE",
"UZUN",
"SAĞDIK",
"ARIKAN YORGUN",
"EKİCİ",
"KESİM",
"GÜL",
"YILDIRIM",
"KARAGÖZ",
"PEKEL",
"YAKAR",
"TARLAN",
"ÇATAK",
"ÇETİNKOR",
"SAYIN",
"KURT",
"GÜMÜŞ",
"KOCAKAYA ALTUNDAL",
"ÖZMEN",
"GÜNAY",
"DÜZ",
"DİLEK",
"DEMİRTAŞ",
"KURTULUŞ",
"KARPUZOĞLU",
"ERGİNTÜRK ACAR",
"BEYOĞLU",
"SULHAN",
"ARSLAN",
"NUHVEREN",
"AVCIOĞLU",
"AHISKALI",
"ASENA",
"KARACAN ERŞEKERCİ",
"GÖLEMEZ",
"YILDIRIM",
"TOHUMOĞLU",
"ÇELİK",
"BOZARSLAN",
"KÖŞKER",
"ÇELİK",
"SÜL",
"KORKMAZ",
"TARKAN",
"DUMAN",
"HODJAOGLU",
"BALLI",
"ŞATIROĞLU",
"ÖNDE",
"LAĞARLI",
"ÖZÇAY",
"ARSLAN",
"AKDEMİR",
"İÇBAY",
"AKIN",
"DEMİRÖZ",
"KUYUCU",
"SELÇUK",
"İNCE",
"ERGÜLÜ EŞMEN",
"GÖKALP",
"BABACAN",
"ÜLGER",
"AYVAZ",
"ELVERDİ",
"AYDIN",
"DEMİREL",
"CİMBEK",
"FIRAT",
"BAHÇEBAŞI",
"DAM",
"KÖROĞLU",
"ÖZÇELİK",
"KARACA",
"SEVEN",
"ÖZKURT",
"ALTUN",
"BÜYÜKTAŞ",
"SERTKAYA",
"ÖVEN USTAALİOĞLU",
"YALNIZ",
"SAVAŞ",
"YILMAZ"};
            var user = _userManager.Users.SingleOrDefault(x => x.UserName == HttpContext.User.Identity.Name);
            var ts = (TimeSpan)(model.EndDate - model.StartDate);

            //CreatePersonal((int)model.PersonalCount, user, nameList, surnameList);
            //CreateCustomer((int)model.CustomerCount, user,nameList,surnameList);

            var personals = _context.Personals.Where(x=>x.CompanyId == user.CompanyId).ToList();

            var startDate = new DateTime(model.StartDate.Value.Year,
                model.StartDate.Value.Month,
                model.StartDate.Value.Day,
                10,
                0, 0, 0);

            var endDate = startDate.AddHours(1);
            //CreateAppointment(user,ts.Days,(int)model.Capacity,personals,startDate,endDate);

            var startDate2 = startDate.AddHours(2);
            var endDate2 = endDate.AddHours(2);
            //CreateAppointment(user, ts.Days, (int)model.Capacity, personals, startDate2, endDate2);

            var startDate3 = startDate2.AddHours(2);
            var endDate3 = endDate2.AddHours(2);
            //CreateAppointment(user, ts.Days, (int)model.Capacity, personals, startDate3, endDate3);

            CreateCustomerAppointments(user);

            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public void CreatePersonal(int loopIndex, AppUser user,List<string> nameList, List<string> surnameList)
        {
            var rnd = new Random();
            for (var i = 0; i < loopIndex; i++)
            {
                var indexCount = rnd.Next(500);
                var personal = new Personal()
                {
                    CompanyId = user.CompanyId,
                    Name = nameList[indexCount] + " " + surnameList[indexCount],
                    Profession = "Duyu Ve Sanat",
                    PhoneNumber = "(555) 666-7788",
                    SeansPrice = 250,
                    CreatedDate = DateTime.Now,
                    CreatedName = user.NormalizedUserName,
                    Status = true
                };

                _context.Add(personal);
            }
            _context.SaveChanges();
        }

        public void CreateCustomer(int loopIndex, AppUser user, List<string> nameList, List<string> surnameList)
        {
            var rnd = new Random();
            for (var i = 0; i < loopIndex; i++)
            {
                var indexCount = rnd.Next(500);
                var childIndex = rnd.Next(500);
                var customer = new Customer()
                {
                    Name = nameList[indexCount],
                    Surname = surnameList[indexCount],
                    ChildName = nameList[childIndex],
                    PhoneNumber = "(555) 555-5555",
                    ChildBirthday = DateTime.Now.AddYears(-3).AddMonths(-2),
                    StoreId = user.CompanyId,
                    CreatedDate = DateTime.Now,
                    CreatedName = user.NormalizedUserName,
                };
                _context.Add(customer);

            }
            _context.SaveChanges();
        }

        public void CreateAppointment(AppUser user, int loopIndex, int capacity,List<Personal>personals,DateTime startDate, DateTime endDate)
        {
            var rnd = new Random();
            for (var i = 0; i < loopIndex; i++)
            {
                var indexPersonal = rnd.Next(10);
                var appointment = new Appointment()
                {
                    Capacity = capacity,
                    CompanyId = user.CompanyId,
                    CreatedDate = DateTime.Now,
                    CreatedName = user.NormalizedUserName,
                    LessonPrice = 150,
                    MaxAge = 5,
                    MinAge = 1,
                    PersonalId = personals[indexPersonal].Id,
                    Subject = "Demo",
                    TeacherPrice = 150,
                    Status = true,
                    PersonalName = personals[indexPersonal].Name,
                    EndDate = startDate,
                    StartDate = endDate,
                };
                _context.Appointments.Add(appointment);

                startDate = startDate.AddDays(1);
                endDate = endDate.AddDays(1);
            }

            _context.SaveChanges();
        }

        public void CreateCustomerAppointments(AppUser user)
        {
            var rnd = new Random();
            var appointments = _context.Appointments.Where(x => x.CompanyId == user.CompanyId).ToList();
            var customers = _context.Customers.Where(x => x.StoreId == user.CompanyId).ToList();

            foreach (var app in appointments)
            {
                var customerAppIndex = rnd.Next(3, 6);
                for (int i = 0; i < customerAppIndex; i++)
                {
                    var customerIndex = rnd.Next(customers.Count());
                    var customerAppointment = new CustomerAppointment()
                    {
                        AppointmentId = app.Id,
                        CustomerId = customers[customerIndex].Id,
                        CreatedDate = DateTime.Now,
                        CreatedName = user.NormalizedUserName,
                        Status = true,
                        PaymentType = (int)PaymentType.Cash,
                        PacketId = null,
                        CompanyId = user.CompanyId,
                        AppointmentDate = app.StartDate
                    };
                    _context.CustomerAppointments.Add(customerAppointment);
                }
                
            }
            _context.SaveChanges();
        }
    }
}